tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/cert.pem
        keyFile: /certs/privkey.pem
  certificates:
    - certFile: /certs/cert.pem
      keyFile: /certs/privkey.pem
